### ISSUE TITLE
Is it possible to full screen

### ISSUE THREAD

**Issue by taimur113311** [AsynctaskCoffee/YoutubeFloatingVideo#5]
Hi, 

Thanks for the awesome Library. 
I need to know one thing. 
Can you please add a full-screen button that shows full-screen youtube video while the popup window is showing or please tell me how to do this.

**Comment by AsynctaskCoffee** [comment]
Fullscreen support is added :)

**Comment by FidaMOhsin** [comment]
Bro full screen means, open popup dialog in full screen . not open new Activity.
Can you add support when user click on maximize the video, it just increase the height and width of popup. Like popup will fit in full screen just like Whatsapp?
